# A SciPy Module for Linear Algebra: scipy.linalg 

Notebook Author: Matthew Kearns

### The reference material for this notebook can be found in the SciPy.org linear algebra module (scipy.linalg) tutorial: https://docs.scipy.org/doc/scipy/reference/tutorial/linalg.html

Notebook Contents:

    - Basics
        - Finding inverses
        - Generalized inverses
        - Finding determinants
        - Computing norms
        - Solving linear systems
        
    - Decompositions
        - Eigenvalues and eigenvectors
        - Singular value decompositions
        - Extras
        
    - Matrix functions
        - Exponential and logarithm functions
        - Trigonometric functions
        - Hyperbolic trigonometric functions
        - Arbitrary functions
        
    - Special matrices
        - Extras
    

### Basics

###### Finding inverses

In [1]:
import numpy as np
from scipy import linalg

In [5]:
# The inverse of matrix A is a matrix B s.t. AB = I
A = np.array([x**2 for x in range(9)]).reshape(3, 3)
A

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [6]:
B = linalg.inv(A)
B

array([[ 0.93055556, -0.61111111,  0.18055556],
       [-1.5       ,  0.66666667, -0.16666667],
       [ 0.625     , -0.16666667,  0.04166667]])

In [8]:
# check result
I = A.dot(B)
I

array([[ 1.00000000e+00,  1.11022302e-16, -2.77555756e-17],
       [ 0.00000000e+00,  1.00000000e+00, -6.66133815e-16],
       [ 0.00000000e+00,  8.88178420e-15,  1.00000000e+00]])

###### Generalized inverses

In [18]:
# we can calculate generalized inverses using linalg.pinv or pinv2

###### Finding determinants

In [10]:
# det(A)
A = np.array([[2, 3, 7], [4, 1, 6], [1, 5, 4]]).reshape(3, 3)
det_A = linalg.det(A)
det_A

51.0

###### Computing norms

In [17]:
# L1, frobenius, and inf norms
A = np.array([1, 2, 3, 4]).reshape(2, 2)
L1 = linalg.norm(A, 1)
L2 = linalg.norm(A) # frobenius norm
inf = linalg.norm(A, np.inf)

print('L1 Norm:', L1, '(max column sum)')
print('L2 Norm:', L2)
print('Inf Norm:', inf, '(max row sum)')

L1 Norm: 6.0 (max column sum)
L2 Norm: 5.477225575051661
Inf Norm: 7.0 (max row sum)


###### Solving linear systems

In [9]:
# solve the system Ax = b
A = np.array([[1, 7, 2], [3, 6, 8], [9, 2, 4]]).reshape(3, 3)
b = np.array([2, 5, 10])
x = linalg.solve(A, b)
x

array([1.01204819, 0.09036145, 0.17771084])

### Decompositions

###### Eigenvalues and eigenvectors

###### Singular value decompositions

###### Extras

### Matrix functions

###### Exponential and logarithm functions

###### Trigonometric functions

###### Hyperbolic trigonometric functions

###### Arbitrary functions

### Special matrices

###### Extras