# A SciPy Module for Linear Algebra: scipy.linalg 

Notebook Author: Matthew Kearns

### The reference material for this notebook can be found in the SciPy.org linear algebra module (scipy.linalg) tutorial: https://docs.scipy.org/doc/scipy/reference/tutorial/linalg.html

Notebook Contents:

    - Basics
        - Finding inverses
        - Generalized inverses
        - Finding determinants
        - Computing norms
        - Solving linear systems
        
    - Decompositions
        - Eigenvalues and eigenvectors
        - Singular value decompositions
        
    - Matrix functions
        - Exponential and logarithm functions
        - Trigonometric functions
        - Hyperbolic trigonometric functions
    

### Basics

###### Finding inverses

In [1]:
import numpy as np
from scipy import linalg

In [5]:
# The inverse of matrix A is a matrix B s.t. AB = I
A = np.array([x**2 for x in range(9)]).reshape(3, 3)
A

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [6]:
B = linalg.inv(A)
B

array([[ 0.93055556, -0.61111111,  0.18055556],
       [-1.5       ,  0.66666667, -0.16666667],
       [ 0.625     , -0.16666667,  0.04166667]])

In [8]:
# check result
I = A.dot(B)
I

array([[ 1.00000000e+00,  1.11022302e-16, -2.77555756e-17],
       [ 0.00000000e+00,  1.00000000e+00, -6.66133815e-16],
       [ 0.00000000e+00,  8.88178420e-15,  1.00000000e+00]])

###### Generalized inverses

In [18]:
# we can calculate generalized inverses using linalg.pinv or pinv2

###### Finding determinants

In [10]:
# det(A)
A = np.array([[2, 3, 7], [4, 1, 6], [1, 5, 4]]).reshape(3, 3)
det_A = linalg.det(A)
det_A

51.0

###### Computing norms

In [17]:
# L1, frobenius, and inf norms
A = np.array([1, 2, 3, 4]).reshape(2, 2)
L1 = linalg.norm(A, 1)
L2 = linalg.norm(A) # frobenius norm
inf = linalg.norm(A, np.inf)

print('L1 Norm:', L1, '(max column sum)')
print('L2 Norm:', L2)
print('Inf Norm:', inf, '(max row sum)')

L1 Norm: 6.0 (max column sum)
L2 Norm: 5.477225575051661
Inf Norm: 7.0 (max row sum)


###### Solving linear systems

In [9]:
# solve the system Ax = b
A = np.array([[1, 7, 2], [3, 6, 8], [9, 2, 4]]).reshape(3, 3)
b = np.array([2, 5, 10])
x = linalg.solve(A, b)
x

array([1.01204819, 0.09036145, 0.17771084])

### Decompositions

###### Eigenvalues and eigenvectors

In [19]:
A = np.array([[2, 4, 1], [5, 4, 2], [1, 6, 2]])
A

array([[2, 4, 1],
       [5, 4, 2],
       [1, 6, 2]])

In [23]:
# finding the m (not necessarily unique) eigenvalues for an
# m x m matrix
eig_vals, eig_vects = linalg.eig(A)

In [24]:
eig_vals

array([ 9.24264069+0.j, -2.        +0.j,  0.75735931+0.j])

In [25]:
eig_vects

array([[ 0.44692133,  0.37139068, -0.28228981],
       [ 0.65760207, -0.55708601, -0.14921712],
       [ 0.60648235,  0.74278135,  0.94765327]])

###### Singular value decompositions

In [27]:
# SVD is an extension of the eigenvalue/eigenvector problem
# extended to non-square matrices
A = np.array([[1, 4, 8], [6, 2, 3]])
A

array([[1, 4, 8],
       [6, 2, 3]])

In [28]:
M, N = A.shape # rows x cols

In [30]:
U, sigma, V_h = linalg.svd(A)
Sig = linalg.diagsvd(sigma, M, N)

In [34]:
print('U:\n', U, end='\n\n')
print('V^H:\n', V_h, end='\n\n')
print('Sigma:\n', Sig, end='\n\n')

U:
 [[-0.83308373 -0.55314691]
 [-0.55314691  0.83308373]]

V^H:
 [[-0.4028357  -0.43064863 -0.80762934]
 [ 0.91180413 -0.11207836 -0.39503376]
 [ 0.07960298 -0.89553347  0.43781636]]

Sigma:
 [[10.30684512  0.          0.        ]
 [ 0.          4.87534037  0.        ]]



In [39]:
# Checking results of computation
U.dot(Sig.dot(V_h))

array([[1., 4., 8.],
       [6., 2., 3.]])

### Matrix functions

###### Exponential and logarithm functions

In [42]:
A = np.array([x+1 for x in range(9)]).reshape(3, 3)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
# the matrix exponential
exp_A = linalg.expm(A)
exp_A

array([[1118906.69941319, 1374815.06293582, 1630724.42645844],
       [2533881.04189899, 3113415.03138058, 3692947.02086216],
       [3948856.38438479, 4852012.99982534, 5755170.61526589]])

In [44]:
# the matrix logarithm
log_A = linalg.logm(A)
log_A

array([[ -5.32112526+2.78963761j,  11.82881173-0.43245193j,
         -5.29483839-0.51294882j],
       [ 12.13859546-0.79703932j, -21.98009977+2.16225964j,
         12.4483792 -1.16162671j],
       [ -4.67527092-1.2421236j ,  12.75816293-1.5262141j ,
         -4.08199032+1.33128805j]])

###### Trigonometric functions

In [48]:
# trigonometric functions on matrices
sin_A = linalg.sinm(A)
cos_A = linalg.cosm(A)
tan_A = linalg.tanm(A)

print('\nsin(A):\n', sin_A)
print('\ncos(A):\n', cos_A)
print('\ntan(A):\n', tan_A)


sin(A):
 [[-0.69279119 -0.23059008  0.23161103]
 [-0.17243208 -0.14335308 -0.11427409]
 [ 0.34792703 -0.05611609 -0.4601592 ]]

cos(A):
 [[ 0.38017733 -0.37383015 -0.12783762]
 [-0.53120649  0.39010533 -0.68858284]
 [-0.44259032 -0.84595919 -0.24932806]]

tan(A):
 [[-1.42972068 -0.3413874   0.74694587]
 [-0.05326132  0.09080172  0.23486477]
 [ 1.32319804  0.52299085 -0.27721634]]


###### Hyperbolic trigonometric functions

In [49]:
# additionally, we can define the hyperbolic trig functions for matrices
sinh_A = linalg.sinhm(A)
cosh_A = linalg.coshm(A)
tanh_A = linalg.tanhm(A)

print('\nsinh(A):\n', sinh_A)
print('\ncosh(A):\n', cosh_A)
print('\ntanh(A):\n', tanh_A)


sinh(A):
 [[ 559452.16451266  687407.39921472  815362.63391679]
 [1266940.5659768  1556707.14935783 1846473.73273887]
 [1974428.96744093 2426006.89950094 2877584.83156095]]

cosh(A):
 [[ 559454.53490054  687407.66372109  815361.79254165]
 [1266940.4759222  1556707.88202275 1846473.2881233 ]
 [1974427.41694386 2426006.1003244  2877585.78370494]]

tanh(A):
 [[-0.46967692 -0.02015569  0.42936554]
 [ 0.18948816  0.29431009  0.39913201]
 [ 0.84865324  0.60877586  0.36889848]]
